apiVersion: skaffold/v2beta19
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: anirbanpupi/auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - dest: .
                    src: 'src/**/*.ts'
        - image: anirbanpupi/client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - dest: .
                    src: '**/*.js'
        - image: anirbanpupi/tickets
          context: tickets
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - dest: .
                    src: '**/*.ts'
        - image: anirbanpupi/orders
          context: orders
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - dest: .
                    src: '**/*.ts'
        - image: anirbanpupi/expiration
          context: expiration
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
        - image: anirbanpupi/payments
          context: payments
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
